accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('signout/', views.signout, name='signout'),
]

calendarapp/urls.py
from django.urls import path

from . import views
from .views import  other_views
#from django.conf.urls.static import static
#from django.conf import settings
app_name = 'calendarapp'


urlpatterns = [
    path('calender/', views.CalendarViewNew.as_view(), name='calendar'),
    #path('', other_views.SubirArchivos(), name='archivos'),
    path('calenders/', views.CalendarView.as_view(), name='calendars'),
    path('event/new/', views.create_event, name='event_new'),
    path(
        'event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'
    ),
    path(
        'event/<int:event_id>/details/', views.event_details,
        name='event-detail'
    ),

    path(
        'add_eventmember/<int:event_id>', views.add_eventmember,
        name='add_eventmember'
    ),
    path(
        'event/<int:pk>/remove', views.EventMemberDeleteView.as_view(),
        name="remove_event"
    ),
    path(
        'all-event-list/', views.AllEventsListView.as_view(),
        name="all_events"
    ),
    path(
        'running-event-list/', views.RunningEventsListView.as_view(),
        name="running_events"
    ),
    path('excel/', other_views.sub_excel, name='excel'),
path(
        'event/aprobacion/<int:event_id>', other_views.agregar_aprobacion,
        name='event-aprobacion'
    ),
]
#if settings.DEBUG:
 #   urlpatterns += static(
  #      settings.MEDIA_URL,
   #     document_root = settings.MEDIA_ROOT
   # )

eventcalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import DashboardView


urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('calendarapp.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from calendarapp.models.linea_presupuesto import Line_Presupuesto
from calendarapp.models import EventAbstract
from accounts.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(
            user=user, is_active=True, is_deleted=False
        )
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user, is_active=True, is_deleted=False,
            end_time__gte=datetime.now().date()
        ).order_by('start_time')
        return running_events


class Event(EventAbstract):
    """ Event model """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='events'
    )
    linea_p = models.ForeignKey(
        Line_Presupuesto, on_delete=models.CASCADE, related_name='events')

    title = models.CharField(max_length=200, unique=False)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    Proyecto = models.CharField(max_length=150)
    Presupuesto = models.FloatField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('calendarapp:event-detail', args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse('calendarapp:event-detail', args=(self.id,))
        return f'{url}'


class upload(models.Model):
    title = models.CharField(max_length=50)
    upload = models.FileField(upload_to="media")

calendarapp/models/event_abstract.py
from django.db import models


class EventAbstract(models.Model):
    """ Event abstract model """
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    is_modificado= models.BooleanField(default=False)
    modificaciones = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

calendarapp/forms.py
from django.forms import ModelForm, DateInput
from calendarapp.models import Event, EventMember
from calendarapp.models.linea_presupuesto import Cronogram
from django import forms


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'start_time', 'end_time']
        # datetime-local is a HTML5 input type
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter eveeeent title'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter event description'
            }),
            'start_time': DateInput(
                attrs={'type': 'datetime-local', 'class': 'form-control'},
                format='%Y-%m-%dT%H:%M'
            ),
            'end_time': DateInput(
                attrs={'type': 'datetime-local', 'class': 'form-control'},
                format='%Y-%m-%dT%H:%M'
            ),
            'Proyecto': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter eveeeent title'
            }),

        }
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class AddMemberForm(forms.ModelForm):
    class Meta:
        model = EventMember
        fields = ['user']

class excel_form(forms.ModelForm):
    class Meta:
        model= Cronogram
        fields = ["Proyecto", "Archivo_excel"]

#form

calendarapp/views/event_list.py
from django.views.generic import ListView, TemplateView
from django.shortcuts import render, redirect
from calendarapp.models import Event, EventMember


class AllEventsListView(ListView):
    """ All event list views """
    template_name = 'calendarapp/events_list.html'
    model = Event

    def get_queryset(self):
        return Event.objects.get_all_events(user=self.request.user)


class RunningEventsListView(TemplateView):
    """ Running events list view """
    template_name = 'calendarapp/events_list.html'
    model = EventMember
    def get(self, request, *args, **kwargs):
        Evento_extra = EventMember.objects.filter(user=self.request.user)
        object_list =[]
        for evento in Evento_extra:
            detallado= Event.objects.get(id=evento.event_id)
            object_list.append(detallado)
        Eventos_Normales= Event.objects.filter(user=self.request.user)
        for e in Eventos_Normales:
            object_list.append(e)
        ctx = {'object_list': object_list}
        return render(request,'calendarapp/events_list.html',ctx)

calendarapp/views/other_views.py
# cal/views.py

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
from datetime import timedelta, datetime, date
import calendar
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
import pandas as pd
from accounts.models import  user
from calendarapp.models import EventMember, Event
from calendarapp.models.event import upload
from calendarapp.models.linea_presupuesto import Cronogram, Line_Presupuesto
from calendarapp.utils import Calendar
from calendarapp.forms import EventForm, AddMemberForm, excel_form
from django.utils.functional import SimpleLazyObject
from django.contrib import messages

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


class CalendarView(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:signin'
    model = Event
    template_name = 'calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


@login_required(login_url='signup')
def create_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        title = form.cleaned_data['title']
        description = form.cleaned_data['description']
        start_time = form.cleaned_data['start_time']
        end_time = form.cleaned_data['end_time']
        l= Line_Presupuesto.objects.first()
        Event.objects.get_or_create(
            user=request.user,
            title=title,
            description=description,
            start_time=start_time,
            end_time=end_time,
            linea_p=l,
            Proyecto="ss",
            Presupuesto=0.0,

        )
        return HttpResponseRedirect(reverse('calendarapp:calendar'))
    return render(request, 'event.html', {'form': form})


class EventEdit(generic.UpdateView):
    model = Event
    fields = ['title', 'description', 'start_time', 'end_time','Presupuesto']
    template_name = 'event.html'


@login_required(login_url='signup')
def agregar_aprobacion(request, event_id):
    if  request.method=="GET":
         return render(request,'Aprobación.html')
    else:
        comentario = request.POST['Comentario']
        aprov = request.POST['Aprobacion']
        value_=True
        if aprov=='0':
            value_=False
        event = EventMember.objects.get(event_id=event_id,user=request.user)
        event.Comentario=comentario
        event.Aprobacion= value_
        event.save()
        link = "/event/"+str(event_id)+"/details/"
        return  redirect(link)


@login_required(login_url='signup')
def event_details(request, event_id):
    event = Event.objects.get(id=event_id)
    eventmember = EventMember.objects.filter(event=event)
    line_id = event.linea_p_id
    linia  = Line_Presupuesto.objects.get(Id=line_id)
    prespuesto = event.Presupuesto
    context = {
        'event': event,
        'eventmember': eventmember,
        'linea': linia,
        'presupuest': prespuesto,
    }
    proyecto = event.Proyecto
    Actualizar_Saldos(proyecto)
    return render(request, 'event-details.html', context)


def add_eventmember(request, event_id):
    forms = AddMemberForm()
    if request.method == 'POST':
        forms = AddMemberForm(request.POST)
        if forms.is_valid():
            member = EventMember.objects.filter(event=event_id)
            event = Event.objects.get(id=event_id)
            if member.count() <= 9:
                user = forms.cleaned_data['user']
                EventMember.objects.create(
                    event=event,
                    user=user
                )
                return redirect('calendarapp:calendar')
            else:
                print('--------------User limit exceed!-----------------')
    context = {
        'form': forms
    }
    return render(request, 'add_member.html', context)


class EventMemberDeleteView(generic.DeleteView):
    model = EventMember
    template_name = 'event_delete.html'
    success_url = reverse_lazy('calendarapp:calendar')


class CalendarViewNew(LoginRequiredMixin, generic.View):
    login_url = 'accounts:signin'
    template_name = 'calendarapp/calendar.html'
    form_class = EventForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        events = Event.objects.get_all_events(user=request.user)
        # Mostrar solo lineas de proyectos participates
        e_partica = Event.objects.filter(user=request.user)
        lineas=[]
        for even in e_partica:
            lina= even.linea_p_id
            if not lina in  lineas:
                lineas.append(lina)
        events_month=[]

        for line_id in lineas:
            Linea_p = Line_Presupuesto.objects.get(Id=line_id)
            events_month.append(Linea_p)

        #events_month = Line_Presupuesto.objects.all()
        event_list = []
        # start: '2020-09-16T16:00:00'
        for event in events:
            event_list.append({
                'title': event.title,
                'start': event.start_time.date().strftime("%Y-%m-%dT%H:%M:%S"),
                'end': event.end_time.date().strftime("%Y-%m-%dT%H:%M:%S"),
            })
        context = {
            'form': forms,
            'events': event_list,
            'events_month': events_month
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            form = forms.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('calendarapp:calendar')
        context = {
            'form': forms
        }
        return render(request, self.template_name, context)


@login_required(login_url='signup')
def sub_excel(request):
    if request.method=='POST':
        form_1 = excel_form(request.POST, request.FILES)
        if form_1.is_valid():
            form_1.save()
        ultimo = Cronogram.objects.last()
        archivo = ultimo.Archivo_excel
        proyecto = ultimo.Proyecto
        user_list = list(user.User.objects.all())
        df = pd.ExcelFile(archivo)
        df1 = df.parse('Consolidado Nacional')
        df2 = df.parse('Presupuesto')

        total= Line_Presupuesto.objects.all().count()
        line_list = list(Line_Presupuesto.objects.all())
        o = [str(i) for i in line_list]


        for u in range (len(df2)):
            if (not (df2['Código'][u] in o)) and (type(df2['Código'][u]) == str):
                total+=1
                Line_Presupuesto.objects.get_or_create(
                    Id=total,
                    Codigo=str(df2['Código'][u]),
                    Total=df2['Presupuesto'][u],
                    Ejecutado=0,
                    En_Ejucucion=0,
                    Saldo=df2['Presupuesto'][u],
                    Proyecto=proyecto,
                )
        line_list1 = list(Line_Presupuesto.objects.all())
        o1 = [str(i) for i in line_list1]
        year = df1['Unnamed: 8'][4]
        year1 = year.split(': ')
        try:
            print(year1[1])
        except IndexError:
            mensaje=f'MENSAJE DE ERROR: Asegurese que en {year} haya un espacio antes del año'
            messages.error(request, mensaje)
            return render(request, 'subir_excel.html')

        actividad = 'sin actividad1'
        for i in range(9, len(df1)):
            act1 = actividad
            actividad = df1['Unnamed: 2'][i]
            if not type(actividad) == str:
                actividad = act1

            unidad_de_medida = df1['Unnamed: 3'][i]
            if not type(unidad_de_medida) == str:
                mensaje ="Error en la columna 'Unidad de medida' en la fila " + str(i+2)
                messages.error(request,mensaje)
                return render(request, 'subir_excel.html')


            cantidad = df1['Unnamed: 4'][i]
            if not type(cantidad) == int:
                mensaje = "Error en la columna 'Cantidad' en la fila " + str(i + 2)
                messages.error(request, mensaje)
                return render(request, 'subir_excel.html')


            encargado = df1['Unnamed: 5'][i]
            if not type(encargado) == str:
                mensaje = f"No asignó encargado a la actividad '{actividad}' en unidad de medida: '{unidad_de_medida}'"
                messages.error(request, mensaje)
                return render(request, 'subir_excel.html')

            responsables = df1['Unnamed: 6'][i]
            if not type(responsables) == str:
                mensaje = f"No asignó responsables a la actividad '{actividad}' en unidad de medida: '{unidad_de_medida}'"
                messages.error(request, mensaje)
                return render(request, 'subir_excel.html')


            lista_responsables = responsables.split(', ')
            lista_responsables.append(encargado)

            linea_presupuestaria = df1['Unnamed: 7'][i]



            if linea_presupuestaria in o1:

templates/calendarapp/calendar.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Event Calendar{% endblock title %}

{% block extracss %}
  <link href="{% static 'calender/main.css' %}" rel="stylesheet" />
{% endblock extracss %}

{% block breadcrumb %}
  <div>
      <h1><i class="fa fa-calendar"></i> Calendario</h1>
      <p>Eventos en calendario</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
      <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
      <li class="breadcrumb-item"><a href="#">Calendar</a></li>
      <li class="breadcrumb-item"><a href="{% url 'calendarapp:excel' %}">Excel</a></li>
  </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="tile row">
            <div class="col-md-3">
                <div id="external-events">
                    <h4 class="mb-4">Lineas Presupuestarias</h4>
                    {% for event in events_month %}
                      <div class="fc-event">
                          <h3>{{ event.Proyecto }}: {{ event.Codigo }}</h3>
                          <p>Total: {{ event.Total }}</p>
                          <p>Ejecutado: {{ event.Ejecutado }}</p>
                          <p>En ejecución: {{ event.En_Ejucucion }}</p>
                           <p>Saldo Disponible: {{ event.Saldo }}</p>
                      </div>
                    {% empty %}
                      <p>Sin eventos en progreso</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-9">
                <div id="calendar"></div>
            </div>

            <div class="modal fade show" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-primary">
                            <h5 class="modal-title text-white" id="exampleModalLongTitle">Agregar nuevo evento</h5>
                            <button id="modalClose1" type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="recipient-name" class="col-form-label">Título del evento:</label>
                                    {{ form.title }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Descripción:</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Fecha de inicio:</label>
                                    {{ form.start_time }}
                                </div>
                                <div class="form-group">
                                    <label for="message-text" class="col-form-label">Fecha de fin:</label>
                                    {{ form.end_time }}
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button id="modalClose2" type="button" class="btn btn-danger">Cerrar</button>
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrascripts %}
  <script src="{% static 'calender/main.js' %}"></script>
  <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var today = new Date();

        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay,list'
          },
          initialDate: today,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          select: function(arg) {
            console.log('clicked')
            var modal = document.getElementById('eventModal')
            modal.style.display = 'block'
            calendar.unselect()
          },
          // THIS KEY WON'T WORK IN PRODUCTION!!!
          // To make your own Google API key, follow the directions here:
          // http://fullcalendar.io/docs/google_calendar/
          // googleCalendarApiKey: 'AIzaSyCqCxjjLtjbtkX37aOtWB8OfwBLy_6QuYk',

          // bangladesh Holidays
          // events: 'bn.bd#holiday@group.v.calendar.google.com',
          eventClick: function(arg) {
              var titulo = arg.event.title
            if (confirm('Quieres modificar el evento: "'+titulo+'"')) {
                var L = titulo.split('#')
                var idevento = L[1]
                window.location.replace("/event/"+ idevento +"/details/")
                            }
          },
          editable: true,
          dayMaxEvents: true, // allow "more" link when too many events
          events: {{ events|safe }},
          // events: [
          //   {
          //     title: 'All Day Event',
          //     start: '2021-06-26'
          //   },
          //   {
          //     groupId: 999,
          //     title: 'Repeating Event',
          //     start: '2020-09-16T16:00:00'
          //   },
          //   {
          //     title: 'Conference',
          //     start: '2020-09-11',
          //     end: '2020-09-13'
          //   },
          //   {
          //     title: 'Click for Google',
          //     url: 'http://google.com/',
          //     start: '2020-09-28'
          //   }
          // ]
        });

        calendar.render();
      });
      const closeBtn1 = document.getElementById('modalClose1');
      const closeBtn2 = document.getElementById('modalClose2');
      closeBtn1.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
      closeBtn2.addEventListener('click',()=>{
        const eventModal = document.getElementById('eventModal')
        eventModal.style.display = 'none';
      });
  </script>
{% endblock extrascripts %}

templates/calendarapp/dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Event Dashboard{% endblock title %}

{% block breadcrumb %}
    <div>
        <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
        <p>Eventos</p>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
    </ul>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-lg-3">
        <div class="widget-small primary coloured-icon">
            <i class="icon fa fa-files-o fa-3x"></i>
            <div class="info">
                <h4>Eventos completos</h4>
                <p><b>{{ total_event }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small info coloured-icon">
            <i class="icon fa fa-thumbs-o-up fa-3x"></i>
            <div class="info">
                <h4>Eventos en ejecución</h4>
                <p><b>{{ running_events.count }}</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small warning coloured-icon">
            <i class="icon fa fa-users fa-3x"></i>
            <div class="info">
                <h4>Total Participantes</h4>
                <p><b>{{ eventmember.count }} </b></p>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="widget-small danger coloured-icon">
            <i class="icon fa fa-star fa-3x"></i>
            <div class="info">
                <h4>Stars</h4>
                <p><b>500</b></p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="table-responsive">
                    <div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid" aria-describedby="sampleTable_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 261.641px;">SL</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 417.312px;">Nombre del evento</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 189.281px;">Inicio</th>
                                            <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 102.141px;">Final</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for event in latest_events %}
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{ forloop.counter }}</td>
                                                <td>{{ event.title }}</td>
                                                <td>{{ event.start_time }}</td>
                                                <td>{{ event.end_time }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

{% block extrascripts %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
{% endblock extrascripts %}